# .dev means we're building this image for development only (run with docker build -f Dockerfile.dev .)
FROM node:22-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm", "run", "start" ]
