# services = containers we want to simultaneously run
services:
  # first container: make a container from redis image
  redis-server:
    image: "redis"
  # second container: build from Dockergile in a directory and map host port to container port
  node-app:
    build: .
    ports:
      - "8080:8080"
